#!/bin/bash

# Phase 6: Configuration Updates
# Updates Jekyll configuration and project files for new structure

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
HELPERS_DIR="$(dirname "$SCRIPT_DIR")/helpers"

# Source helper functions
source "$HELPERS_DIR/utils.sh"
source "$HELPERS_DIR/mapping.sh"
source "$HELPERS_DIR/validation.sh"

phase6_config_updates() {
    local dry_run="${1:-false}"
    
    log_info "=== Phase 6: Configuration Updates ==="
    
    if [[ "$dry_run" == "true" ]]; then
        log_info "🔍 DRY RUN MODE - No files will be modified"
    fi
    
    local updated_files=0
    local error_files=0
    
    # Update Jekyll _config.yml
    if update_jekyll_config "$dry_run"; then
        ((updated_files++))
    else
        ((error_files++))
    fi
    
    # Update course structure data file
    if update_course_structure_data "$dry_run"; then
        ((updated_files++))
    else
        ((error_files++))
    fi
    
    # Update navigation includes
    if update_navigation_includes "$dry_run"; then
        ((updated_files++))
    else
        ((error_files++))
    fi
    
    # Update index page
    if update_index_page "$dry_run"; then
        ((updated_files++))
    else
        ((error_files++))
    fi
    
    # Create new module index pages
    if create_module_index_pages "$dry_run"; then
        ((updated_files++))
    else
        ((error_files++))
    fi
    
    # Update assets references
    if update_asset_references "$dry_run"; then
        ((updated_files++))
    else
        ((error_files++))
    fi
    
    # Summary
    log_info "Configuration Updates Summary:"
    log_info "  Successfully updated: $updated_files"
    log_info "  Errors: $error_files"
    
    if [[ "$dry_run" == "false" ]]; then
        if ((error_files > 0)); then
            log_warn "Phase 6 completed with $error_files errors"
            return 1
        else
            log_success "Phase 6: Configuration Updates completed successfully!"
        fi
    else
        log_info "Phase 6: Configuration Updates dry run completed!"
    fi
    
    return 0
}

# Update Jekyll configuration
update_jekyll_config() {
    local dry_run="$1"
    
    log_info "Updating Jekyll _config.yml..."
    
    if [[ ! -f "_config.yml" ]]; then
        log_warn "_config.yml not found, creating basic one"
        if [[ "$dry_run" == "false" ]]; then
            create_basic_jekyll_config
        fi
        return 0
    fi
    
    if [[ "$dry_run" == "true" ]]; then
        log_info "WOULD UPDATE: _config.yml with new structure paths"
        return 0
    fi
    
    # Backup original
    cp "_config.yml" "_config.yml.backup.$(date +%s)"
    
    # Add/update collections for modules
    if ! grep -q "collections:" "_config.yml"; then
        echo "" >> "_config.yml"
        echo "# Collections for course modules" >> "_config.yml"
        echo "collections:" >> "_config.yml"
        echo "  modules:" >> "_config.yml"
        echo "    output: true" >> "_config.yml"
        echo "    permalink: /:collection/:name/" >> "_config.yml"
    fi
    
    # Update plugins if needed
    if ! grep -q "jekyll-sitemap" "_config.yml"; then
        if grep -q "plugins:" "_config.yml"; then
            sed -i.tmp '/plugins:/a\
  - jekyll-sitemap' "_config.yml"
        else
            echo "" >> "_config.yml"
            echo "plugins:" >> "_config.yml"
            echo "  - jekyll-sitemap" >> "_config.yml"
        fi
        rm -f "_config.yml.tmp"
    fi
    
    log_success "Updated _config.yml"
    return 0
}

# Update course structure data file
update_course_structure_data() {
    local dry_run="$1"
    
    log_info "Updating course structure data..."
    
    if [[ "$dry_run" == "true" ]]; then
        log_info "WOULD UPDATE: _data/course_structure.yml with new module structure"
        return 0
    fi
    
    # Backup original
    if [[ -f "_data/course_structure.yml" ]]; then
        cp "_data/course_structure.yml" "_data/course_structure.yml.backup.$(date +%s)"
    fi
    
    # Create new structure file
    mkdir -p "_data"
    cat > "_data/new_course_structure.yml" << 'EOF'
# New Course Structure - Generated by Migration Script
# Course: Estrutura de Dados e Algoritmos

course:
  title: "Estrutura de Dados e Algoritmos"
  description: "Curso completo de estruturas de dados e algoritmos"
  version: "2.0"
  last_updated: 
  
modules:
EOF
    
    # Add current date
    sed -i.tmp "s/last_updated:.*/last_updated: \"$(date +'%Y-%m-%d')\"/" "_data/new_course_structure.yml"
    rm -f "_data/new_course_structure.yml.tmp"
    
    # Generate module entries
    get_all_module_mappings | while IFS='|' read -r old_name new_id new_title; do
        cat >> "_data/new_course_structure.yml" << EOF
  - id: $new_id
    title: "$new_title"
    path: "modules/$new_id"
    lessons_path: "modules/$new_id/lessons"
    exercises_path: "modules/$new_id/exercises"
    examples_path: "modules/$new_id/examples"
    resources_path: "modules/$new_id/resources"
    audio_path: "assets/audio/$new_id"
EOF
    done
    
    log_success "Created new course structure data file"
    return 0
}

# Update navigation includes
update_navigation_includes() {
    local dry_run="$1"
    
    log_info "Updating navigation includes..."
    
    if [[ "$dry_run" == "true" ]]; then
        log_info "WOULD UPDATE: Navigation includes for new structure"
        return 0
    fi
    
    mkdir -p "_includes"
    
    # Create module navigation include
    cat > "_includes/module_navigation.html" << 'EOF'
<!-- Module Navigation -->
<nav class="module-nav">
  <h3>Módulos do Curso</h3>
  <ul class="module-list">
    {% for module in site.data.new_course_structure.modules %}
    <li class="module-item">
      <a href="{{ module.path | relative_url }}" class="module-link">
        <span class="module-id">{{ module.id }}</span>
        <span class="module-title">{{ module.title }}</span>
      </a>
      
      <!-- Sub-navigation for current module -->
      {% if page.module_id == module.id %}
      <ul class="module-subnav">
        <li><a href="{{ module.lessons_path | relative_url }}">Aulas</a></li>
        <li><a href="{{ module.exercises_path | relative_url }}">Exercícios</a></li>
        <li><a href="{{ module.examples_path | relative_url }}">Exemplos</a></li>
        <li><a href="{{ module.resources_path | relative_url }}">Recursos</a></li>
      </ul>
      {% endif %}
    </li>
    {% endfor %}
  </ul>
</nav>
EOF
    
    # Create audio player include
    cat > "_includes/audio_player.html" << 'EOF'
<!-- Audio Player for Lessons -->
{% if page.audio_file %}
<div class="audio-player">
  <h4>🎧 Áudio da Aula</h4>
  <audio controls preload="metadata">
    <source src="{{ site.baseurl }}/assets/audio/{{ page.module_id }}/{{ page.audio_file }}" type="audio/mpeg">
    Seu navegador não suporta o elemento de áudio.
  </audio>
</div>
{% endif %}
EOF
    
    log_success "Updated navigation includes"
    return 0
}

# Update index page
update_index_page() {
    local dry_run="$1"
    
    log_info "Updating index page..."
    
    if [[ "$dry_run" == "true" ]]; then
        log_info "WOULD UPDATE: index.md with new course structure"
        return 0
    fi
    
    # Backup original if exists
    if [[ -f "index.md" ]]; then
        cp "index.md" "index.md.backup.$(date +%s)"
    fi
    
    # Create updated index page
    cat > "index.md" << 'EOF'
---
layout: default
title: "Estrutura de Dados e Algoritmos"
description: "Curso completo de estruturas de dados e algoritmos com exemplos práticos"
---

# Estrutura de Dados e Algoritmos

Bem-vindo ao curso completo de **Estrutura de Dados e Algoritmos**! 

## 📚 Sobre o Curso

Este curso oferece uma abordagem completa e prática para o aprendizado de estruturas de dados e algoritmos, com foco em implementações reais e aplicações práticas.

## 🎯 Módulos do Curso

{% for module in site.data.new_course_structure.modules %}
<div class="module-card">
  <h3><a href="{{ module.path | relative_url }}">{{ module.id | upcase }}: {{ module.title }}</a></h3>
  <div class="module-links">
    <a href="{{ module.lessons_path | relative_url }}" class="btn btn-primary">Aulas</a>
    <a href="{{ module.exercises_path | relative_url }}" class="btn btn-secondary">Exercícios</a>
    <a href="{{ module.examples_path | relative_url }}" class="btn btn-info">Exemplos</a>
  </div>
</div>
{% endfor %}

## 🚀 Como Usar

1. **Navegue pelos módulos** na ordem sugerida
2. **Assista as aulas** com áudio explicativo
3. **Pratique com exercícios** de diferentes níveis
4. **Estude os exemplos** de código fornecidos
5. **Use os recursos** adicionais para aprofundar

## 📖 Recursos Adicionais

- [Documentação do Curso](docs/)
- [Exemplos de Código](examples/)
- [Exercícios Práticos](exercises/)

---

*Curso criado e mantido como projeto open source.*
EOF
    
    log_success "Updated index page"
    return 0
}

# Create module index pages
create_module_index_pages() {
    local dry_run="$1"
    
    log_info "Creating module index pages..."
    
    if [[ "$dry_run" == "true" ]]; then
        log_info "WOULD CREATE: Index pages for each module"
        return 0
    fi
    
    # Create index page for each module
    get_all_module_mappings | while IFS='|' read -r old_name new_id new_title; do
        local module_dir="modules/$new_id"
        
        if [[ -d "$module_dir" ]]; then
            cat > "$module_dir/index.md" << EOF
---
layout: module
title: "$new_title"
module_id: $new_id
description: "Módulo $new_id do curso de Estrutura de Dados e Algoritmos"
---

# $new_title

## 📖 Sobre este Módulo

Este módulo aborda os conceitos fundamentais de **$new_title**.

## 📚 Conteúdo

### Aulas
{% assign lessons = site.pages | where: "module_id", "$new_id" | where: "content_type", "lesson" %}
{% for lesson in lessons %}
- [{{ lesson.title }}]({{ lesson.url | relative_url }})
{% endfor %}

### Exercícios
{% assign exercises = site.pages | where: "module_id", "$new_id" | where: "content_type", "exercise" %}
{% for exercise in exercises %}
- [{{ exercise.title }}]({{ exercise.url | relative_url }})
{% endfor %}

### Exemplos
{% assign examples = site.pages | where: "module_id", "$new_id" | where: "content_type", "example" %}
{% for example in examples %}
- [{{ example.title }}]({{ example.url | relative_url }})
{% endfor %}

## 🎧 Recursos de Áudio

Os áudios deste módulo estão disponíveis em: \`assets/audio/$new_id/\`

---

[← Voltar ao Curso]({{ site.baseurl }}/) | [Próximo Módulo →]()
EOF
        fi
    done
    
    log_success "Created module index pages"
    return 0
}

# Update asset references in existing files
update_asset_references() {
    local dry_run="$1"
    
    log_info "Updating asset references..."
    
    if [[ "$dry_run" == "true" ]]; then
        log_info "WOULD UPDATE: Asset references in CSS/JS files"
        return 0
    fi
    
    # Update CSS files
    find assets/css -name "*.css" -type f 2>/dev/null | while read -r css_file; do
        if [[ -f "$css_file" ]]; then
            sed -i.bak 's|src/modulos-treinamento/|modules/|g' "$css_file" 2>/dev/null || true
            rm -f "$css_file.bak" 2>/dev/null || true
        fi
    done
    
    # Update JS files
    find assets/js -name "*.js" -type f 2>/dev/null | while read -r js_file; do
        if [[ -f "$js_file" ]]; then
            sed -i.bak 's|src/modulos-treinamento/|modules/|g' "$js_file" 2>/dev/null || true
            rm -f "$js_file.bak" 2>/dev/null || true
        fi
    done
    
    log_success "Updated asset references"
    return 0
}

# Create basic Jekyll config if none exists
create_basic_jekyll_config() {
    cat > "_config.yml" << 'EOF'
# Jekyll Configuration for Estrutura de Dados e Algoritmos

title: "Estrutura de Dados e Algoritmos"
description: "Curso completo de estruturas de dados e algoritmos"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Collections
collections:
  modules:
    output: true
    permalink: /:collection/:name/

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - scripts/
  - backups/
  - README.md

# Include files
include:
  - .htaccess

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Default front matter
defaults:
  - scope:
      path: "modules"
    values:
      layout: "module"
      course: "estrutura-de-dados-e-algoritmos"
EOF
}

# Rollback configuration updates
rollback_phase6() {
    local backup_id="$1"
    
    log_info "Rolling back Phase 6: Configuration Updates (Backup ID: $backup_id)"
    
    # Restore backup files
    find . -name "*.backup.*" -type f 2>/dev/null | while read -r backup_file; do
        local original_file="${backup_file%%.backup.*}"
        if [[ -f "$backup_file" ]]; then
            mv "$backup_file" "$original_file"
            log_info "Restored: $original_file"
        fi
    done
    
    # Remove generated files
    rm -f "_data/new_course_structure.yml" 2>/dev/null || true
    rm -f "_includes/module_navigation.html" 2>/dev/null || true
    rm -f "_includes/audio_player.html" 2>/dev/null || true
    
    # Remove module index pages
    find modules -name "index.md" -type f -delete 2>/dev/null || true
    
    log_success "Phase 6 rollback completed"
}

# Main execution (if script is run directly)
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    DRY_RUN="${1:-false}"
    phase6_config_updates "$DRY_RUN"
fi 